### ISSUE TITLE
Redirection to an MVC controller makes the web application crash

### ISSUE THREAD

**Issue by leye0** [Runscope/dotnet-messagehandler#2]
When redirecting from an email to an MVC controller, I get a crash. I had to add a constructor with blacklisted keywords to allow me to bypass certain requests.

The crash looks like it:

This method or property is not supported after HttpRequest.GetBufferlessInputStream has been invoked.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Web.HttpException: This method or property is not supported after HttpRequest.GetBufferlessInputStream has been invoked.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[HttpException (0x80004005): This method or property is not supported after HttpRequest.GetBufferlessInputStream has been invoked.]
   System.Web.HttpRequest.EnsureFiles() +3274885
   System.Web.HttpRequest.get_Files() +12
   System.Web.HttpRequestWrapper.get_Files() +28
   System.Web.Mvc.HttpFileCollectionValueProvider.GetHttpPostedFileDictionary(ControllerContext controllerContext) +36
   System.Web.Mvc.HttpFileCollectionValueProviderFactory.GetValueProvider(ControllerContext controllerContext) +30
   System.Web.Mvc.ValueProviderFactoryCollection.GetValueProvider(ControllerContext controllerContext) +69
   System.Web.Mvc.ControllerBase.get_ValueProvider() +25
   System.Web.Mvc.ControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor) +62
   System.Web.Mvc.ControllerActionInvoker.GetParameterValues(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +105
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState) +743
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +14
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state) +328
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1c(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState) +25
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +30
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state) +556
   System.Web.Mvc.Controller.<BeginExecute>b__14(AsyncCallback asyncCallback, Object callbackState, Controller controller) +18
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +20
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +420
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +16
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState) +52
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +30
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +369
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) +48
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +16
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +301
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by darrelmiller** [comment]
Thanks for reporting this.

I have to admit, I've never tried using this on an MVC based site.  I'm not familiar with the GetBufferlessInputStream method but I'm pretty sure I know what is going wrong.  I intentionally buffer request and response bodies so that they can be read twice.  What I might be able to do is for these cases where I'm not allowed to buffer the bodies is just post to Runscope without the bodies.

I will need to investigate to find out how to detect if I'm not allowed to buffer,

**Comment by darrelmiller** [comment]
@leye0 Would it be possible to provide some more details about the actual requests that causes this error.  What I don't understand is, the stack trace that you are showing doesn't include the the RunscopeApiMessageHandler. Also, when MVC requests are handled they don't pass through the Web API Message Processing pipeline.

Any additional information you could provide that would help me reproduce this error would be much appreciated.

**Comment by leye0** [comment]
When debugging more deeply, in Visual Studio, the crash stops in the ExecuteCore method of the MvcController if I add all overrides, and this is when CreateActionInvoker. It seems like just adding handlers everywhere is enough to make Mvc crash. When searching about this error, I saw cases of user using loggers, just like in this case. What I've made is adding the handler in the route, and this is way more nice:

            config.Routes.MapHttpRoute(
            name: "DefaultApi",
            routeTemplate: "api/{controller}/{id}",
            defaults: new { id = RouteParameter.Optional }, 
            constraints: null, 
            handler: runscopeHandler);

**Comment by darrelmiller** [comment]
That's good to know and a clever solution.  I still don't understand why adding a message handler to the configuration.MessageHandlers collection has any impact on MVC.  Strange.

**Comment by leye0** [comment]
There is the beginning of a analysis here to handle different exception
case. Not that much related but interesting.
https://azure.microsoft.com/en-us/documentation/articles/app-insights-asp-net-exceptions/
